[ADJUST]: moving level from scores to users
brunoapollon/Multiplica-api pull request #3
Opened 2021-07-16 22:57 UTC by brunoapollon

Movendo level de scores para users com todas modificações necessárias

2021-07-18 14:29 UTC, lunebakami requested changes

2021-07-18 14:29 UTC, lunebakami commented on src/controllers/UserController.js
> +
Adicionar verificação do tipo do usuário, pois caso ele não seja do tipo 1, ele não terá level

2021-07-18 14:29 UTC, lunebakami commented on src/database/index.js
Refatorar para utilizar o array models para iniciar as conexões

2021-07-19 11:29 UTC, lunebakami commented on src/controllers/UserController.js
> +    const { enrollment } = request;
Por que da remoção do ".params"?

2021-07-19 12:38 UTC, brunoapollon commented on src/controllers/UserController.js
> +    const { enrollment } = request;
pq o show é onde o user vai ver os dados dele, então ele tem que ta autenticado pra isso

2021-07-19 14:39 UTC, lunebakami commented on src/controllers/UserController.js
> +    const { enrollment } = request;
no caso o enrollment é colocado no request pelo método de autenticação certo?

2021-07-19 15:10 UTC, brunoapollon commented on src/controllers/UserController.js
> +    const { enrollment } = request;
Sim sim. Se tu quiser olhar o middleware pra confirmar. Mas é isso mesmo, na autenticação eu coloco enrollment no request

2021-07-19 19:02 UTC, merged